/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import string_Encrypt_Decrypt.StringEncryptFunction;

/**
 *
 * @author Admin
 */
public class Page_nhaplieu extends javax.swing.JFrame {

    /**
     * Creates new form Page_nhaplieu
     */
    public Page_nhaplieu() {
        initComponents();
        

    }

    public void maHoa() {
        String encryptedMsg = StringEncryptFunction.EncryptString(StringEncryptFunction.plainTextToHexString(txt_PlainText.getText()),
                StringEncryptFunction.plainTextToHexString(txt_KeyText.getText()));
        String decryptedMsg = StringEncryptFunction.DecryptString(encryptedMsg,
                StringEncryptFunction.plainTextToHexString( txt_KeyText.getText()));
        txt_EncryptedMess.setText(encryptedMsg);
        txt_DercyptedMess.setText(StringEncryptFunction.hexToString(decryptedMsg));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_PlainText = new javax.swing.JTextField();
        txt_KeyText = new javax.swing.JTextField();
        txt_EncryptedMess = new javax.swing.JTextField();
        txt_DercyptedMess = new javax.swing.JTextField();
        btn_MaHoa = new javax.swing.JButton();
        btn_giaiMa = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Decrypted message:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 140, 32));

        jLabel2.setText("Plain text");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 128, 71));

        jLabel3.setText("Key text:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 140, 32));

        jLabel4.setText("Encrypted message:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 140, 32));
        getContentPane().add(txt_PlainText, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 440, 67));
        getContentPane().add(txt_KeyText, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 440, 30));

        txt_EncryptedMess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_EncryptedMessActionPerformed(evt);
            }
        });
        getContentPane().add(txt_EncryptedMess, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 440, 30));

        txt_DercyptedMess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_DercyptedMessActionPerformed(evt);
            }
        });
        getContentPane().add(txt_DercyptedMess, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 440, 30));

        btn_MaHoa.setBackground(new java.awt.Color(255, 204, 204));
        btn_MaHoa.setText("Giải mã");
        getContentPane().add(btn_MaHoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 260, 120, 40));

        btn_giaiMa.setBackground(new java.awt.Color(102, 255, 102));
        btn_giaiMa.setText("Mã hóa");
        btn_giaiMa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_giaiMaActionPerformed(evt);
            }
        });
        getContentPane().add(btn_giaiMa, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 260, 120, 40));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 790, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 330, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_EncryptedMessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_EncryptedMessActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_EncryptedMessActionPerformed

    private void txt_DercyptedMessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_DercyptedMessActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_DercyptedMessActionPerformed

    private void btn_giaiMaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_giaiMaActionPerformed
        maHoa();
    }//GEN-LAST:event_btn_giaiMaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Page_nhaplieu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Page_nhaplieu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Page_nhaplieu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Page_nhaplieu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Page_nhaplieu page = new Page_nhaplieu();
                page.setLocationRelativeTo(null);
                page.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_MaHoa;
    private javax.swing.JButton btn_giaiMa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txt_DercyptedMess;
    private javax.swing.JTextField txt_EncryptedMess;
    private javax.swing.JTextField txt_KeyText;
    private javax.swing.JTextField txt_PlainText;
    // End of variables declaration//GEN-END:variables
}
